# Generated by Django 4.2.28 on 2026-04-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_url',
            field=models.URLField(blank=True, help_text='Logo URL (e.g. simpleicons.org)'),
        ),
    ]
