# Generated by Django 6.0.4 on 2026-04-29 08:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_skill_icon_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='video_url',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='video_embed',
            field=models.TextField(blank=True, help_text='Paste YouTube/Vimeo embed iframe code here'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
