# Generated by Django 6.0.4 on 2026-04-29 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_galleryitem_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='video_embed',
        ),
    ]
